import { createSlice } from "@reduxjs/toolkit";

// Retrieve stored notes data from local storage or initialize as null
const storedNotes = localStorage.getItem("noteData");
const initialState = {
    notesData: storedNotes ? JSON.parse(storedNotes) : null // Parse storedNotes if it exists, otherwise initialize as null
};

// Create a note slice
const noteSlice = createSlice({
    name: "note", // Name of the slice
    initialState: initialState, // Initial state
    reducers: {
        // Reducer to set notes data
        setNotesData(state, action) {
            state.notesData = action.payload; // Update notesData with payload data
        }
    }
});

// Export actions generated by createSlice
export const { notesData, setNotesData } = noteSlice.actions;

// Export the reducer generated by createSlice
export default noteSlice.reducer;
